# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from centml_client.models.compilation_status import CompilationStatus

class TestCompilationStatus(unittest.TestCase):
    """CompilationStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompilationStatus(self):
        """Test CompilationStatus"""
        # inst = CompilationStatus()

if __name__ == '__main__':
    unittest.main()
