# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install --pre --extra-index-url https://download.hidet.org/whl hidet
        pip install .
    - name: Test with pytest
      run: |
        cd ./tests
        pytest --sanity
